site:
  title: Oracle SQL Features
  url: https://oracle-sql-features.github.io
  start_page: guide::index.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./ui-bundle.zip
  supplemental_files: ./supplemental_ui

asciidoc:
  extensions:
    - ./extensions/remote-include-processor/extension
    - ./extensions/tabs-block/extension
