name: Push

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle

      - name: Generate navigation
        shell: bash
        run: |
          java .github/scripts/generate_navigation.java "$(pwd)"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Run Antora
        run: npx antora antora-playbook.yml

      - name: Copy site
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/website
          cp -rf $GITHUB_WORKSPACE/build/site/* $GITHUB_WORKSPACE/website
          touch $GITHUB_WORKSPACE/website/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          folder: website
          branch: 'gh-pages'
          commit-message: "[CI] Publish Documentation for ${{ github.sha }}"
