name: Site

on:
  workflow_dispatch:

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Generate navigation
        shell: bash
        run: sh generate.sh

      - name: Copy site
        shell: bash
        run: |
          mkdir -p website
          cp -rf build/site/* website
          touch website/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          folder: website
          branch: 'gh-pages'
          commit-message: "[CI] Publish Documentation for ${{ github.sha }}"
